### PR TITLE
Simplified Tables: Example on Users List

### PR DESCRIPTION
**Pull request by lukasbuenger**
Changelog:
- refactor `components/Users/List/TableBody.js` and  `components/Users/List/TableHead.js` into one component `Table.js` using HTML5 tables in combination with `position: sticky`.

Reasoning:
- We could get rid of `react-sticky-el`.
- We could get rid of the micro-abstractions in `components/Layout` (in the long run). 
- Easier handling of tables because not scattered between files.

### CODE REVIEW

**Review by tpreusse — APPROVED** [review]
Getting ride of dependencies ist fantastisch. Go for it!

**Comment by lukasbuenger** [comment]
@tpreusse All the tables are refactored. Might want to have a look.

Also, there is `components/base/tables` which aims at collecting everything that's used in all tables in a domain specific way: Instead of 
`import tableStyles from 'styles/tables`
you would
`import { tableStyles } from 'base/tables`

I don't know if `base` is a good namespace but it feels better than `utils`.

**Review by tpreusse — APPROVED** [review]
LGTM.

I'd rename `components/base/tables.js` into `components/Tables/utils.js` (preferred) or move that code to `lib/utils/tables.js`.

**Comment by lukasbuenger** [comment]
Will do! Thanks for checking

**Pull request merged**
